### ISSUE TITLE
heap corruption 

### ISSUE THREAD

**Issue by muteb** [janstarke/dionysos#1]
Hi Jan,

I really like this project and thank you for including the evtx and reg into the scanner very helpful. I have compiled this on windows and found out that if when increasing the multi-threading number to the available ones on my machine or using the default one 16 or even decrease it the 3 or 4, it will have conflict and cause heap corruption. Noticeably, this corruption happens when scanning very very large files :(.

Thanks,

**Comment by janstarke** [comment]
Does the bug disappear if you don't enable scanning of compressed files (don't set the `-C` switch)?

Can you please provide a stack trace (run with `RUST_BACKTRACE=all`) ?

Kind regards, Jan

**Comment by muteb** [comment]
Hi Jan,
sorry for the late response. 
No the compress files option was not enabled and it didn't contain any panic traces rather it showed only the system heap corruption error as below. 
`error: process didn't exit successfully: `target\debug\dionysos.exe -Y c:\allrules\NewRules.yar` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)`
 Keep in mind I didn't specify any thread number and I'm only using the default. My first thought is that if multi threading was running while these threads contains very large files to scan, the Yara lib might be the main cause of it. I kind modified the code to oly scan the files that are less than 30 mb and it worked fine and I think this error has nothing to do with library rather it is Yara lib just saying :). 
 
 I have seeing multiple projects using https://github.com/rayon-rs/rayon as they solved such issue. You might have a look at it.
 
 Thanks

**Comment by janstarke** [comment]
I tried to migrate to rayon in the 1-heap-corruption branch. Could you please try if that fixes the problem?
